// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService 是基于 trpc-agent-go 的对话 Agent 服务:
 *   - 每次 Chat 按会话所选 Provider/Model 动态构建 LLMAgent,会话可并行
 *   - 办公能力(待办/统计/日志)以 function calling 暴露
 *   - <数据目录>/skills 下的 SKILL.md 由框架加载,新增即插即用
 * 
 * 流式增量经事件 agent.chunk 推给前端,开始/结束为 agent.start / agent.done。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbandonPlan closes an active plan without changing conversation history.
 */
export function AbandonPlan(req: $models.PlanActionRequest): $CancellablePromise<void> {
    return $Call.ByID(3253605054, req);
}

/**
 * Chat 执行一轮 Agent 对话;流式增量通过事件推给前端。
 */
export function Chat(req: $models.ChatRequest): $CancellablePromise<$models.ChatResult> {
    return $Call.ByID(103566506, req);
}

/**
 * DeleteConversation 删除会话及其消息。
 */
export function DeleteConversation(conversationID: number): $CancellablePromise<void> {
    return $Call.ByID(1677379224, conversationID);
}

/**
 * ExecutePlan immediately executes the exact approved revision.
 */
export function ExecutePlan(req: $models.PlanActionRequest): $CancellablePromise<$models.ChatResult> {
    return $Call.ByID(3504225524, req);
}

/**
 * ListConversations 返回会话列表(近期在前)。
 */
export function ListConversations(): $CancellablePromise<$models.Conversation[] | null> {
    return $Call.ByID(1379328896);
}

/**
 * MessagesSnapshot returns the application-level ordered conversation timeline.
 * The underlying AG-UI snapshot remains internal so plan entities never masquerade as chat messages.
 */
export function MessagesSnapshot(conversationID: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3734322460, conversationID);
}

/**
 * RevisePlan creates a complete new revision using the conversation's currently selected model.
 */
export function RevisePlan(req: $models.PlanActionRequest): $CancellablePromise<$models.ChatResult> {
    return $Call.ByID(1232929119, req);
}

/**
 * SetConversationModel changes only the selected conversation. New conversations still inherit the global default.
 */
export function SetConversationModel(req: $models.SetConversationModelRequest): $CancellablePromise<void> {
    return $Call.ByID(2043989792, req);
}
