// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApplicationService exposes build metadata to the desktop UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Version returns the version embedded in the running executable.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3439552345);
}
