// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(4221804060, id);
}

export function Export(id: string, version: number): $CancellablePromise<void> {
    return $Call.ByID(3629241805, id, version);
}

export function Get(id: string, version: number): $CancellablePromise<$models.ArtifactRef> {
    return $Call.ByID(4169255513, id, version);
}

export function Import(): $CancellablePromise<$models.ArtifactRef | null> {
    return $Call.ByID(1424628334);
}

export function List(search: string, kind: string, deleted: boolean): $CancellablePromise<$models.ArtifactRef[] | null> {
    return $Call.ByID(2404191367, search, kind, deleted);
}

export function Open(id: string, version: number): $CancellablePromise<void> {
    return $Call.ByID(4265192259, id, version);
}

export function Preview(id: string, version: number): $CancellablePromise<$models.ArtifactPreview> {
    return $Call.ByID(1361048585, id, version);
}

export function Restore(id: string): $CancellablePromise<void> {
    return $Call.ByID(1723671911, id);
}

export function SaveMessage(request: $models.SaveMessageArtifactRequest): $CancellablePromise<$models.ArtifactRef> {
    return $Call.ByID(699713169, request);
}

export function Versions(id: string): $CancellablePromise<$models.ArtifactRef[] | null> {
    return $Call.ByID(3047088118, id);
}
