// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardService reads Windows clipboard text/images and owns extraction drafts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConfirmTodos(req: $models.ConfirmClipboardTodosReq): $CancellablePromise<$models.Todo[] | null> {
    return $Call.ByID(1400733498, req);
}

export function DiscardDraft(draftID: string): $CancellablePromise<void> {
    return $Call.ByID(3747301450, draftID);
}

export function ExtractTodos(): $CancellablePromise<$models.ClipboardTodoDraft> {
    return $Call.ByID(3340436561);
}
