// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddMemory(input: $models.MemoryInput): $CancellablePromise<$models.MemoryItem> {
    return $Call.ByID(545781662, input);
}

export function ClearMemories(): $CancellablePromise<void> {
    return $Call.ByID(292160644);
}

export function DeleteMemory(id: string): $CancellablePromise<void> {
    return $Call.ByID(1391769978, id);
}

export function ExportMemories(): $CancellablePromise<string> {
    return $Call.ByID(126856199);
}

export function GetSettings(): $CancellablePromise<$models.MemorySettingsView> {
    return $Call.ByID(979579879);
}

export function ListMemories(): $CancellablePromise<$models.MemoryItem[] | null> {
    return $Call.ByID(2084385969);
}

export function SaveSettings(input: $models.MemoryConfigInput): $CancellablePromise<$models.MemorySettingsView> {
    return $Call.ByID(1325215790, input);
}

export function UpdateMemory(input: $models.MemoryUpdateInput): $CancellablePromise<$models.MemoryItem> {
    return $Call.ByID(3765036808, input);
}
