// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelPendingApprovals(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2158907213, sessionID);
}

export function GetPermissionState(): $CancellablePromise<$models.PermissionState> {
    return $Call.ByID(4285051486);
}

export function ResolveApproval(id: string, decision: $models.ApprovalDecision): $CancellablePromise<void> {
    return $Call.ByID(3033644485, id, decision);
}

export function RevokeSessionGrant(sessionID: string, grantID: string): $CancellablePromise<void> {
    return $Call.ByID(1278513726, sessionID, grantID);
}

export function SetPermissionMode(mode: $models.PermissionMode): $CancellablePromise<void> {
    return $Call.ByID(3304205462, mode);
}
