// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillDependencyService detects, installs and runs isolated Skill environments.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConfirmSkillDependencyPlan(name: string, plan: $models.SkillDependencyPlan): $CancellablePromise<$models.SkillDependencyPlan> {
    return $Call.ByID(4082965830, name, plan);
}

/**
 * GenerateSkillDependencyPlan asks the configured model for a reviewable draft.
 * It never writes the draft or installs dependencies.
 */
export function GenerateSkillDependencyPlan(name: string): $CancellablePromise<$models.SkillDependencyPlan> {
    return $Call.ByID(1908167089, name);
}

export function GetSkillEnvironmentStatus(name: string): $CancellablePromise<$models.SkillEnvironmentStatus> {
    return $Call.ByID(765621163, name);
}

export function InitializeSkill(name: string): $CancellablePromise<$models.SkillEnvironmentStatus> {
    return $Call.ByID(986318292, name);
}

export function InspectSkillDependencies(name: string): $CancellablePromise<$models.SkillDependencyPlan> {
    return $Call.ByID(4149005637, name);
}

export function ListRuntimeStatus(): $CancellablePromise<$models.SkillRuntimeStatus[] | null> {
    return $Call.ByID(1006426829);
}

export function RemoveSkillEnvironment(name: string): $CancellablePromise<void> {
    return $Call.ByID(1747324703, name);
}

export function RepairSkillEnvironment(name: string): $CancellablePromise<$models.SkillEnvironmentStatus> {
    return $Call.ByID(1971844930, name);
}
