// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VocabularyService owns saved terms and their review progress.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddSelectedText(text: string): $CancellablePromise<$models.VocabularyWord> {
    return $Call.ByID(509316582, text);
}

/**
 * AddWord inserts a term or returns the existing case-insensitive match.
 */
export function AddWord($in: $models.VocabularyWordInput): $CancellablePromise<$models.VocabularyWord> {
    return $Call.ByID(770993084, $in);
}

/**
 * AddWords validates the full batch before atomically inserting or merging it.
 */
export function AddWords(inputs: $models.VocabularyWordInput[] | null): $CancellablePromise<$models.VocabularyWord[] | null> {
    return $Call.ByID(650491613, inputs);
}

export function CreateReview(count: number): $CancellablePromise<$models.VocabularyReview> {
    return $Call.ByID(1317564873, count);
}

export function DeleteWord(id: number): $CancellablePromise<void> {
    return $Call.ByID(1288366766, id);
}

export function GenerateSentence(ids: number[] | null): $CancellablePromise<string> {
    return $Call.ByID(648133775, ids);
}

export function GetWord(id: number): $CancellablePromise<$models.VocabularyWord> {
    return $Call.ByID(2287484123, id);
}

export function ListWords(query: string): $CancellablePromise<$models.VocabularyWord[] | null> {
    return $Call.ByID(2050300278, query);
}

/**
 * RandomWords draws terms uniformly without changing review progress.
 */
export function RandomWords(count: number): $CancellablePromise<$models.VocabularyWord[] | null> {
    return $Call.ByID(1926804319, count);
}

export function RecordReview(ids: number[] | null, mastered: boolean): $CancellablePromise<void> {
    return $Call.ByID(2518292208, ids, mastered);
}

export function Stats(): $CancellablePromise<$models.VocabularyStats> {
    return $Call.ByID(3061537740);
}

export function UpdateWord($in: $models.VocabularyWordInput): $CancellablePromise<$models.VocabularyWord> {
    return $Call.ByID(2647178044, $in);
}
