// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as app$0 from "../../../../AntNoHuabei/Miel/internal/app/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "agent.agui": { [_ in string]?: any } | null;
            "agent.chunk": { [_ in string]?: any } | null;
            "agent.done": { [_ in string]?: any } | null;
            "agent.input.saved": { [_ in string]?: any } | null;
            "agent.start": { [_ in string]?: any } | null;
            "artifacts.changed": string;
            "clipboard.todo.show": string;
            "conversations.changed": string;
            "memory.changed": string;
            "memory.status": app$0.MemoryStatus;
            "models.changed": string;
            "permission.cancelled": app$0.ApprovalRequest;
            "permission.changed": app$0.PermissionState;
            "permission.expired": app$0.ApprovalRequest;
            "permission.requested": app$0.ApprovalRequest;
            "permission.resolved": { [_ in string]?: any } | null;
            "quickchat.show": string;
            "reminders.changed": string;
            "screenshot.captured": { [_ in string]?: any } | null;
            "screenshot.processed": { [_ in string]?: any } | null;
            "screenshot.saved": { [_ in string]?: any } | null;
            "skill.dependency.confirmation-required": app$0.SkillDependencyPlan;
            "skill.dependency.detected": app$0.SkillDependencyPlan;
            "skill.dependency.failed": app$0.SkillEnvironmentStatus;
            "skill.dependency.progress": app$0.SkillInstallProgress;
            "skill.dependency.ready": app$0.SkillEnvironmentStatus;
            "time": string;
            "todo.source.changed": number;
            "todos.changed": string;
        }
    }
}
