// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService 是基于 trpc-agent-go 的对话 Agent 服务:
 *   - 每次 Chat 按“默认 Provider”动态构建 LLMAgent,会话可并行
 *   - 办公能力(待办/统计/日志)以 function calling 暴露
 *   - <数据目录>/skills 下的 SKILL.md 由框架加载,新增即插即用
 * 
 * 流式增量经事件 agent.chunk 推给前端,开始/结束为 agent.start / agent.done。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Chat 执行一轮 Agent 对话;流式增量通过事件推给前端。
 */
export function Chat(req: $models.ChatRequest): $CancellablePromise<$models.ChatResult> {
    return $Call.ByID(144777739, req);
}

/**
 * DeleteConversation 删除会话及其消息。
 */
export function DeleteConversation(conversationID: number): $CancellablePromise<void> {
    return $Call.ByID(3497914249, conversationID);
}

/**
 * ListConversations 返回会话列表(近期在前)。
 */
export function ListConversations(): $CancellablePromise<$models.Conversation[] | null> {
    return $Call.ByID(2066596987);
}

/**
 * MessagesSnapshot 通过 AG-UI MessagesSnapshot 重放持久化 track events。
 * 返回值保持标准 MESSAGES_SNAPSHOT JSON 结构,前端可直接渲染 messages。
 */
export function MessagesSnapshot(conversationID: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1314565245, conversationID);
}

/**
 * SetNotify 注入事件广播回调(main 装配时设置)。
 */
export function SetNotify(fn: any): $CancellablePromise<void> {
    return $Call.ByID(2856966782, fn);
}
