// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatAttachmentService owns chat image drafts and persisted attachment files.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DiscardDrafts removes composer drafts that have not been sent.
 */
export function DiscardDrafts(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(581332801, ids);
}

/**
 * GetImageDataURI loads the original image on demand for the preview overlay.
 */
export function GetImageDataURI(id: string): $CancellablePromise<string> {
    return $Call.ByID(2094388814, id);
}

/**
 * PasteImage stages the Windows clipboard image. Text-only clipboards return nil.
 */
export function PasteImage(): $CancellablePromise<$models.ChatAttachmentDraft | null> {
    return $Call.ByID(3347024309);
}

/**
 * PickImages opens a Wails native multi-file picker and stages the selection.
 */
export function PickImages(): $CancellablePromise<$models.ChatAttachmentDraft[] | null> {
    return $Call.ByID(4090137570);
}
