// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DirectoryService exposes the canonical application layout to Wails clients.
 * Business services use the same manager internally, so UI diagnostics and runtime paths cannot drift.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * OpenDataDir opens the managed application root in Windows Explorer.
 */
export function OpenDataDir(): $CancellablePromise<void> {
    return $Call.ByID(651618190);
}

/**
 * Paths returns the current locations of databases, logs, sources, attachments and outputs.
 */
export function Paths(): $CancellablePromise<$models.DirectoryPaths> {
    return $Call.ByID(1730443277);
}
