// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddMemory(input: $models.MemoryInput): $CancellablePromise<$models.MemoryItem> {
    return $Call.ByID(2531929303, input);
}

export function ClearMemories(): $CancellablePromise<void> {
    return $Call.ByID(3459452801);
}

export function DeleteMemory(id: string): $CancellablePromise<void> {
    return $Call.ByID(3543467989, id);
}

export function ExportMemories(): $CancellablePromise<string> {
    return $Call.ByID(2458202904);
}

export function GetSettings(): $CancellablePromise<$models.MemorySettingsView> {
    return $Call.ByID(3742061642);
}

export function ListMemories(): $CancellablePromise<$models.MemoryItem[] | null> {
    return $Call.ByID(4222189258);
}

export function SaveSettings(input: $models.MemoryConfigInput): $CancellablePromise<$models.MemorySettingsView> {
    return $Call.ByID(4275059381, input);
}

export function UpdateMemory(input: $models.MemoryUpdateInput): $CancellablePromise<$models.MemoryItem> {
    return $Call.ByID(349733079, input);
}
