// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AskShotReq 截图问答入参。
 */
export interface AskShotReq {
    "shotId": number;
    "question": string;
}

/**
 * CatalogModel 目录中的单个模型。
 */
export interface CatalogModel {
    "id": string;
    "label": string;
    "reasoning": ReasoningSpec;

    /**
     * 是否支持图片输入(视觉)
     */
    "multimodal": boolean;
}

/**
 * CatalogProvider 目录中的服务商及其模型列表。
 */
export interface CatalogProvider {
    "kind": string;
    "name": string;
    "baseUrl": string;
    "models": CatalogModel[] | null;
}

/**
 * ChatAttachmentDraft is returned to a composer after an image has been staged.
 */
export interface ChatAttachmentDraft {
    "id": string;
    "name": string;
    "mimeType": string;
    "size": number;
    "width": number;
    "height": number;
    "thumbnailDataUri": string;
}

/**
 * ChatMetrics records provider-reported token usage plus wall-clock timing for one assistant reply.
 */
export interface ChatMetrics {
    "model": string;
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
    "reasoningTokens": number;
    "cachedTokens": number;
    "durationMs": number;
    "firstTokenMs": number;
    "tokensPerSecond": number;
}

/**
 * ChatRequest 一次对话入参。
 */
export interface ChatRequest {
    /**
     * 0 = 新建会话
     */
    "conversationId": number;
    "message": string;

    /**
     * "" 默认/关闭 | off | on | low | medium | high | xhigh | max
     */
    "reasoning": string;
    "requestId": string;
    "attachmentIds": string[] | null;
}

/**
 * ChatResult 一次对话的结果(前端可据此刷新会话)。
 */
export interface ChatResult {
    "conversationId": number;
    "answer": string;
    "metrics"?: ChatMetrics | null;
}

export interface ClipboardTodoDraft {
    "draftId": string;
    "kind": string;
    "text": string;
    "dataUri": string;
    "createdAt": number;
    "items": ExtractedTodo[] | null;
}

export interface ConfirmClipboardTodosReq {
    "draftId": string;
    "items": ExtractedTodo[] | null;
}

/**
 * ConfirmExtractedReq 前端确认后批量入库的入参。
 */
export interface ConfirmExtractedReq {
    "shotId": number;
    "items": ExtractedTodo[] | null;
}

/**
 * Conversation 会话元信息。
 */
export interface Conversation {
    "id": number;
    "title": string;
    "createdAt": number;
    "updatedAt": number;
}

/**
 * DirectoryPaths is the stable, inspectable path contract for the application.
 * Database files intentionally remain at the root for compatibility with prior releases.
 */
export interface DirectoryPaths {
    "root": string;
    "database": string;
    "aguiDatabase": string;
    "memoryDatabase": string;
    "logs": string;
    "logFile": string;
    "screenshots": string;
    "sources": string;
    "clipboardSources": string;
    "skills": string;
    "outputs": string;
    "reports": string;
    "documents": string;
    "tables": string;
    "memories": string;
    "attachments": string;
    "chatAttachments": string;
    "chatDrafts": string;
    "chatFiles": string;
    "chatThumbnails": string;
}

/**
 * DiscoveredModel 是从 OpenAI 兼容服务动态发现的模型及能力。
 */
export interface DiscoveredModel {
    "id": string;
    "status": string;
    "reasoning": ReasoningSpec;
    "multimodal": boolean;
}

/**
 * Event 操作日志条目,是周报自动汇总的事实来源。
 */
export interface Event {
    "id": number;
    "ts": number;

    /**
     * todo.created / todo.done / screenshot.added / report.generated ...
     */
    "type": string;
    "summary": string;
    "refId": number;
}

/**
 * ExtractedTodo 视觉模型从截图提取的待办(供前端预览确认)。
 */
export interface ExtractedTodo {
    "title": string;
    "description": string;
    "milestone": boolean;

    /**
     * YYYY-MM-DD 或 YYYY-MM-DD HH:MM,可为空
     */
    "dueDate": string;
}

export interface MemoryConfig {
    "enabled": boolean;
    "autoExtract": boolean;
    "strategy": string;
    "customPrompt": string;
}

export type MemoryConfigInput = MemoryConfig;

export interface MemoryInput {
    "content": string;
    "topics": string[] | null;
    "kind": string;
    "eventTime": string;
    "participants": string[] | null;
    "location": string;
}

export interface MemoryItem {
    "id": string;
    "content": string;
    "topics": string[] | null;
    "kind": string;
    "eventTime": string;
    "participants": string[] | null;
    "location": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface MemorySettingsView {
    "config": MemoryConfig;
    "strategies": MemoryStrategyDefinition[] | null;
    "effectivePrompt": string;
    "currentModel": string;
    "status": MemoryStatus;
}

export interface MemoryStatus {
    "state": string;
    "pendingJobs": number;
    "lastSuccessAt": string;
    "lastError": string;
}

export interface MemoryStrategyDefinition {
    "id": string;
    "name": string;
    "description": string;
    "risk": string;
    "prompt": string;
}

export interface MemoryUpdateInput {
    "id": string;
    "content": string;
    "topics": string[] | null;
    "kind": string;
    "eventTime": string;
    "participants": string[] | null;
    "location": string;
}

/**
 * ModelOption 模型切换下拉的扁平选项(provider × 启用模型)。
 */
export interface ModelOption {
    "providerId": number;
    "providerName": string;
    "kind": string;
    "model": string;
    "label": string;
    "custom": boolean;

    /**
     * 是否为当前使用模型
     */
    "isDefault": boolean;
}

/**
 * PingResult 联通测试返回给前端的结构化结果。
 */
export interface PingResult {
    "ok": boolean;
    "message": string;
    "model": string;
    "latencyMs": number;
}

/**
 * Provider 模型服务商配置。
 * Kind 对应 trpc-agent-go 的 provider 体系:
 * 
 * 	openai / anthropic / ollama / deepseek / qwen / hunyuan / herdsman / custom
 * 
 * 其中 herdsman 与 custom 均使用 OpenAI 兼容协议。
 */
export interface Provider {
    "id": number;
    "name": string;
    "kind": string;
    "baseUrl": string;
    "apiKey": string;
    "model": string;

    /**
     * 是否支持图片输入(截图转待办/问答需要)
     */
    "multimodal": boolean;
    "isDefault": boolean;
    "createdAt": number;
}

/**
 * ProviderInput 保存 Provider 的入参(前端设置页表单)。
 */
export interface ProviderInput {
    "id": number;
    "name": string;
    "kind": string;
    "baseUrl": string;
    "apiKey": string;

    /**
     * 当前使用模型
     */
    "model": string;
    "multimodal": boolean;
    "isDefault": boolean;

    /**
     * 启用的模型集合(留空=仅 Model)
     */
    "models": ProviderModelInput[] | null;
}

/**
 * ProviderModel 服务商启用的单个模型(内置或自定义)。
 */
export interface ProviderModel {
    "model": string;
    "label": string;
    "custom": boolean;
}

/**
 * ProviderModelInput 前端提交的启用模型条目。
 */
export interface ProviderModelInput {
    "model": string;
    "label": string;
    "custom": boolean;
}

/**
 * ProviderTemplate 内置厂商模板(设置向导里供选择)。
 */
export interface ProviderTemplate {
    "name": string;
    "kind": string;
    "baseUrl": string;
    "model": string;
    "multimodal": boolean;
    "docsUrl": string;
}

/**
 * ReasoningSpec 描述一个模型的思考/推理支持方式。
 */
export interface ReasoningSpec {
    /**
     * toggle | effort | always | none
     */
    "type": string;

    /**
     * effort 档位(low/medium/high/max)
     */
    "levels"?: string[] | null;

    /**
     * 面向用户的中文说明
     */
    "note"?: string;
}

/**
 * SaveShotReq “仅保存”动作入参。
 */
export interface SaveShotReq {
    "id": number;
    "note": string;
}

/**
 * ScreenshotResult 一次截图的结果(前端弹菜单预览/后续处理)。
 */
export interface ScreenshotResult {
    "id": number;
    "path": string;

    /**
     * JPEG 预览(data URI)
     */
    "dataUri": string;
    "width": number;
    "height": number;
    "createdAt": number;
}

/**
 * Setting 应用设置项(key-value)。
 */
export interface Setting {
    "key": string;
    "value": string;
}

/**
 * Todo 待办项(含里程碑标记)。
 */
export interface Todo {
    "id": number;
    "title": string;
    "description": string;

    /**
     * unix 秒;0 表示无截止时间
     */
    "deadline": number;
    "isMilestone": boolean;

    /**
     * pending | doing | done
     */
    "status": string;

    /**
     * manual | chat | screenshot
     */
    "source": string;
    "sourceId": number;
    "createdAt": number;
    "doneAt": number;
}

/**
 * TodoInput 创建 / 更新待办的入参。
 */
export interface TodoInput {
    "id": number;
    "title": string;
    "description": string;
    "deadline": number;
    "isMilestone": boolean;
    "status": string;
    "source": string;
    "sourceId": number;
}

/**
 * TodoSource preserves the immutable input that produced one or more todos.
 */
export interface TodoSource {
    "id": number;
    "kind": string;
    "textContent": string;
    "filePath": string;
    "mimeType": string;
    "dataUri": string;
    "conversationId": number;
    "messageId": number;
    "conversationTitle": string;
    "conversationAvailable": boolean;
    "screenshotId": number;
    "screenshotNote": string;
    "createdAt": number;
    "available": boolean;
    "error": string;
}

/**
 * TodoStats 提供给前端快捷视图的汇总(角标/里程碑倒计时)。
 */
export interface TodoStats {
    "total": number;
    "pending": number;
    "done": number;
    "milestones": number;

    /**
     * 逾期未完成
     */
    "overdue": number;

    /**
     * 24 小时内到期未完成
     */
    "dueSoon": number;
}

/**
 * Workspace 是用户可选的工作目录。
 */
export interface Workspace {
    "name": string;
    "path": string;
    "isCurrent": boolean;
}
