// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TodoService 负责待办 / 里程碑的 CRUD 与操作日志,并向前端广播变更。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTodo 新增待办并写操作日志。
 */
export function CreateTodo($in: $models.TodoInput): $CancellablePromise<$models.Todo> {
    return $Call.ByID(3838720110, $in);
}

/**
 * DeleteTodo 删除待办并写日志。
 */
export function DeleteTodo(id: number): $CancellablePromise<void> {
    return $Call.ByID(3890522589, id);
}

/**
 * GetTodo 按 ID 读取单个待办。
 */
export function GetTodo(id: number): $CancellablePromise<$models.Todo> {
    return $Call.ByID(1203534646, id);
}

/**
 * ListEvents 返回操作日志;since > 0 时只返回该时间点之后(周报等按周聚合)。
 */
export function ListEvents(since: number): $CancellablePromise<$models.Event[] | null> {
    return $Call.ByID(2267199011, since);
}

/**
 * ListTodos 返回全部待办(调用方自行过滤/排序,数据量小)。
 */
export function ListTodos(): $CancellablePromise<$models.Todo[] | null> {
    return $Call.ByID(3106814143);
}

/**
 * SetTodoStatus 快捷改状态(勾选完成 / 重开)。
 */
export function SetTodoStatus(id: number, status: string): $CancellablePromise<$models.Todo> {
    return $Call.ByID(2489415572, id, status);
}

/**
 * TodoStats 计算快捷视图汇总数据(角标与里程碑提醒)。
 */
export function TodoStats(): $CancellablePromise<$models.TodoStats> {
    return $Call.ByID(283741193);
}

/**
 * UpdateTodo 更新待办的信息字段与状态;状态流转为 done 时写完成日志。
 */
export function UpdateTodo($in: $models.TodoInput): $CancellablePromise<$models.Todo> {
    return $Call.ByID(3290844979, $in);
}
