// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowThemeService 把前端皮肤选择同步给宿主窗口。
 * 具体的窗口 API 由 Windows 实现绑定到原生 HWND。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * SetTheme 同步前端皮肤 ID 到原生窗口。
 */
export function SetTheme(themeID: string): $CancellablePromise<void> {
    return $Call.ByID(2485286056, themeID);
}
