// 皮肤(主题)系统定义。
// 每套皮肤 = antd token(交给 ConfigProvider 的算法/令牌)+ CSS 变量
// (供自定义样式的背景/边框使用,变量以 --bm- 前缀注入 <html>)。
// 新增皮肤:在此追加一项即可,运行时热切换、设置持久化(key: theme)。

export interface BMTheme {
  /** 皮肤 id,同时作为持久化设置值 */
  id: string
  /** 显示名 */
  name: string
  /** 说明 */
  desc: string
  /** 是否暗色(决定 antd 算法) */
  dark: boolean
  /** antd 主题令牌(colorPrimary 等) */
  token: Record<string, string | number>
  /** CSS 变量映射(--bm-{key}) */
  vars: Record<string, string>
}

export const BM_THEMES: BMTheme[] = [
  {
    id: 'light',
    name: '明亮',
    desc: '经典亮色 · 默认',
    dark: false,
    token: { colorPrimary: '#1677ff', borderRadius: 6 },
    vars: {
      'app-bg': '#f5f6f8',
      'content-bg': '#f5f6f8',
      'header-bg': '#ffffff',
      'inset-bg': '#f6f8fa',
      'border': '#f0f0f0',
      'divider': '#dfe3e8',
      'sidebar-bg': '#ffffff',
      'hover-bg': '#f3f4f6',
      'selected-bg': '#e8edf3',
      'selected-text': '#172033',
      'text': '#1f2329',
      'muted': '#667085',
      'signal': '#1677ff',
      'control-radius': '6px',
    },
  },
  {
    id: 'dark',
    name: '暗夜',
    desc: '深色护眼 · 适合夜间',
    dark: true,
    token: { colorPrimary: '#61a8ff', borderRadius: 6 },
    vars: {
      'app-bg': '#0e1116',
      'content-bg': '#141821',
      'header-bg': '#1a1f2a',
      'inset-bg': '#1e2430',
      'border': '#2a3140',
      'divider': '#343d4d',
      'sidebar-bg': '#11161f',
      'hover-bg': '#202734',
      'selected-bg': '#293241',
      'selected-text': '#f3f6fb',
      'text': '#e8edf5',
      'muted': '#98a3b5',
      'signal': '#61a8ff',
      'control-radius': '6px',
    },
  },
  {
    id: 'forest',
    name: '护眼绿',
    desc: '柔和的绿色亮色主题',
    dark: false,
    token: { colorPrimary: '#3a7d44', borderRadius: 6 },
    vars: {
      'app-bg': '#eef4ee',
      'content-bg': '#eef4ee',
      'header-bg': '#ffffff',
      'inset-bg': '#f2f7f1',
      'border': '#e2ecdf',
      'divider': '#cfdccc',
      'sidebar-bg': '#f8fbf7',
      'hover-bg': '#edf3eb',
      'selected-bg': '#dfeadd',
      'selected-text': '#1d3c23',
      'text': '#203126',
      'muted': '#607264',
      'signal': '#3a7d44',
      'control-radius': '6px',
    },
  },
  {
    id: 'nebula',
    name: '极客紫',
    desc: '深色 · 紫色高亮',
    dark: true,
    token: { colorPrimary: '#a78bfa', borderRadius: 6 },
    vars: {
      'app-bg': '#0d0b16',
      'content-bg': '#151222',
      'header-bg': '#1b1730',
      'inset-bg': '#201b38',
      'border': '#2c2547',
      'divider': '#3b3357',
      'sidebar-bg': '#12101d',
      'hover-bg': '#211c34',
      'selected-bg': '#2a2440',
      'selected-text': '#f5f2ff',
      'text': '#f0ebff',
      'muted': '#a69fc1',
      'signal': '#a78bfa',
      'control-radius': '6px',
    },
  },
  {
    id: 'graphite',
    name: '石墨',
    desc: '中性灰阶与红色信号',
    dark: false,
    token: { colorPrimary: '#e4002b', colorBgBase: '#f7f7f6', colorTextBase: '#242424', colorBorder: '#d5d5d2', borderRadius: 4 },
    vars: {
      'app-bg': '#f3f3f2',
      'content-bg': '#f7f7f6',
      'header-bg': '#ffffff',
      'inset-bg': '#efefed',
      'border': '#e5e5e3',
      'divider': '#d5d5d2',
      'sidebar-bg': '#fafaf9',
      'hover-bg': '#efefed',
      'selected-bg': '#e2e2df',
      'selected-text': '#171717',
      'text': '#242424',
      'muted': '#6b6b66',
      'signal': '#e4002b',
      'control-radius': '4px',
    },
  },
  {
    id: 'celadon',
    name: '青瓷',
    desc: '清透青绿浅色主题',
    dark: false,
    token: { colorPrimary: '#007f73', colorBgBase: '#f3f8f7', colorTextBase: '#1c302d', colorBorder: '#bdd4cf', borderRadius: 6 },
    vars: {
      'app-bg': '#edf5f4',
      'content-bg': '#f3f8f7',
      'header-bg': '#fbfdfc',
      'inset-bg': '#e7f1ef',
      'border': '#dbe8e5',
      'divider': '#bdd4cf',
      'sidebar-bg': '#f7fbfa',
      'hover-bg': '#e8f2f0',
      'selected-bg': '#d5e8e4',
      'selected-text': '#143b35',
      'text': '#1c302d',
      'muted': '#5c746f',
      'signal': '#007f73',
      'control-radius': '6px',
    },
  },
  {
    id: 'cinnabar',
    name: '朱砂',
    desc: '冷白底与克制红色强调',
    dark: false,
    token: { colorPrimary: '#c9362b', colorBgBase: '#faf8f7', colorTextBase: '#332725', colorBorder: '#dfcfcb', borderRadius: 6 },
    vars: {
      'app-bg': '#f5f1f0',
      'content-bg': '#faf8f7',
      'header-bg': '#fffdfc',
      'inset-bg': '#f3ecea',
      'border': '#eadfdd',
      'divider': '#dfcfcb',
      'sidebar-bg': '#fbf8f7',
      'hover-bg': '#f3eae8',
      'selected-bg': '#eadbd7',
      'selected-text': '#53211c',
      'text': '#332725',
      'muted': '#77635f',
      'signal': '#c9362b',
      'control-radius': '6px',
    },
  },
  {
    id: 'amber',
    name: '琥珀',
    desc: '暖黑底与琥珀色信号',
    dark: true,
    token: { colorPrimary: '#f0b429', colorBgBase: '#12110e', colorTextBase: '#f4f0e5', colorBorder: '#45402f', borderRadius: 6 },
    vars: {
      'app-bg': '#12110e',
      'content-bg': '#181711',
      'header-bg': '#1d1b14',
      'inset-bg': '#242116',
      'border': '#332f22',
      'divider': '#45402f',
      'sidebar-bg': '#15140f',
      'hover-bg': '#292619',
      'selected-bg': '#38311b',
      'selected-text': '#fff5d6',
      'text': '#f4f0e5',
      'muted': '#aaa28d',
      'signal': '#f0b429',
      'control-radius': '6px',
    },
  },
  {
    id: 'abyss',
    name: '深海',
    desc: '蓝黑底与青色信号',
    dark: true,
    token: { colorPrimary: '#27c7b8', colorBgBase: '#091312', colorTextBase: '#e4f2f0', colorBorder: '#294541', borderRadius: 6 },
    vars: {
      'app-bg': '#08100f',
      'content-bg': '#0d1817',
      'header-bg': '#11201e',
      'inset-bg': '#162623',
      'border': '#203632',
      'divider': '#294541',
      'sidebar-bg': '#0a1514',
      'hover-bg': '#172926',
      'selected-bg': '#203632',
      'selected-text': '#edfffc',
      'text': '#e4f2f0',
      'muted': '#8aa9a4',
      'signal': '#27c7b8',
      'control-radius': '6px',
    },
  },
  {
    id: 'contrast',
    name: '高对比',
    desc: '纯黑底与高可见度黄色',
    dark: true,
    token: { colorPrimary: '#ffd400', colorBgBase: '#000000', colorTextBase: '#ffffff', colorBorder: '#595959', borderRadius: 4 },
    vars: {
      'app-bg': '#000000',
      'content-bg': '#050505',
      'header-bg': '#000000',
      'inset-bg': '#111111',
      'border': '#303030',
      'divider': '#595959',
      'sidebar-bg': '#050505',
      'hover-bg': '#171717',
      'selected-bg': '#292929',
      'selected-text': '#ffffff',
      'text': '#ffffff',
      'muted': '#c4c4c4',
      'signal': '#ffd400',
      'control-radius': '4px',
    },
  },
]

export const DEFAULT_THEME_ID = 'light'

export function themeById(id: string | null | undefined): BMTheme {
  return BM_THEMES.find((t) => t.id === id) ?? BM_THEMES[0]
}
